### PR TITLE
Add support for BC6H, BC7, DXT10 headers and mipmaps

### PR DESCRIPTION
**Pull request by ghost**
* Add support for BC6H/BC7 formats
* Add support for DXT10 headers
* Refactor mipmap handling, works now
* Add support for texture arrays
* Add public function to check magic bytes
* Add loadFile variant that takes a FileInputStream
* Removed debug output and throw errors as exceptions

### CODE REVIEW

**Comment by Mudbill** [comment]
Nice work. How coincidental that only yesterday did I fiddle with this and add BC5 support as well.
Quick question: why remove the debug messages? They may or may not be very useful, but I figured there's no harm in them being there.

**Comment by ghost** [comment]
I figured that usually you would get that information by inspecting objects through a debugger rather than dumping all the info to the log.

**Comment by ghost** [comment]
Oh I didn't actually mention this in the commit message, but BC4 and BC5 support is also added for DDS files with the DXT10 header.

**Comment by Mudbill** [comment]
Ah, well the BC5 support I added is for the standard header, so I guess it still has some purpose. As for the debug stuff, I probably should be updating my habits.

**Comment by ghost** [comment]
That fits together perfectly then, if you merge your BC4 and BC5 support in the old header with my BC1 through 7 support in the new header then we've covered all compressed formats.

**Comment by ghost** [comment]
Also you might have noticed that the code no longer relies on `dwPitchOrLinearSize`. That's done because it is not available consistently and the Microsoft documentation discourages relying on it. But it's pretty easy to calculate it from the height and width which we need to do anyway for mip maps to support non-square textures.

**Comment by Mudbill** [comment]
Indeed it is unreliable. I must've overlooked it if I made my code dependent on it, as I only intended to include it for completeness.

**Comment by ghost** [comment]
I've hidden it completely since exposing it even for completeness will lead to confusion. Anyone needing the size of the image should look at the size of the byte buffer for the mip level they're interested in.

**Comment by ghost** [comment]
I see you've pushed your code, I'll rebase this PR and resolve the conflicts.

**Comment by Mudbill** [comment]
Alright, I was gonna look into the merge in the morning, but that would certainly help.

**Comment by ghost** [comment]
I've finished rebasing the pull request.

**Pull request merged**
